name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dependencies:
    runs-on: ubuntu-latest
    concurrency:
      group: build-dependencies-group
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Poetry dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ./example-app/.venv
          key: ${{ runner.os }}-poetry-venv-${{ hashFiles('example-app/poetry.lock') }}
      
      - name: Install Poetry
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install Dependencies
        working-directory: ./example-app
        run: poetry install --no-root

  static-tests:
    runs-on: ubuntu-latest
    needs: build-dependencies
    concurrency:
      group: static-tests-group
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Poetry dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ./example-app/.venv
          key: ${{ runner.os }}-poetry-venv-${{ hashFiles('example-app/poetry.lock') }}

      - name: Run Static Code Analysis (Linter)
        working-directory: ./example-app
        run: poetry run task lint

      - name: Run Security Tests
        working-directory: ./example-app
        run: poetry run task security

  unit-tests:
    runs-on: ubuntu-latest
    needs: build-dependencies
    concurrency:
      group: unit-tests-group
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Poetry dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ./example-app/.venv
          key: ${{ runner.os }}-poetry-venv-${{ hashFiles('example-app/poetry.lock') }}

      - name: Run Unit Tests
        working-directory: ./example-app
        run: poetry run task test
