name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install Dependencies
        working-directory: ./example-app
        run: poetry install --no-root

  static_tests:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install Dependencies
        working-directory: ./example-app
        run: poetry install --no-root
        
      - name: Run Linting
        working-directory: ./example-app
        run: poetry run task lint
        
      - name: Run Formatting
        working-directory: ./example-app
        run: poetry run task formatter
        
      - name: Run Security Checks
        working-directory: ./example-app
        run: poetry run task security
